<?php

declare(strict_types=1);

namespace Parisek\TimberKit;

/**
 * Generates and installs the two WordPress drop-ins that serve the theme's
 * prerendered outage screen.
 *
 * WordPress shows a fallback screen in two states this covers, and in neither
 * is a theme loaded:
 *
 * - a `.maintenance` file in the site root — written by
 *   `wp maintenance-mode activate`, and by core itself during every core and
 *   plugin update. Read by `wp_maintenance()` in `wp-settings.php`, before
 *   plugins and theme.
 * - an unreachable database — `wpdb::dead_db()`, with no options table to ask
 *   anything of.
 *
 * Both call `require_once` on their drop-in and then `die()`, and neither
 * sends a status header first. So the drop-in owns its own `503` and
 * `Retry-After`, and it must never `return` early: control does not go back to
 * WordPress, it goes to `die()`, and a returning drop-in produces a blank page.
 *
 * **The generated files depend on nothing.** No Composer autoloader, no
 * WordPress function beyond the `WP_CONTENT_DIR` constant, no database. At the
 * moment they run, that is all there is. This class is therefore a source-code
 * generator rather than a runtime: what ships to `wp-content/` is a flat file
 * a human can read in ten seconds.
 *
 * The screen they serve is prerendered by `parisek/styleguide`'s
 * `maintenance:render`. See the theme's own outage documentation.
 */
class OutageDropIns {

	/**
	 * Drop-in filename => the state it covers, for messages.
	 */
	public const DROP_INS = array(
		'maintenance.php' => 'deploy or core update',
		'db-error.php'    => 'database unreachable',
	);

	/**
	 * Where the theme's render command writes the screen, relative to the
	 * theme root. Fixed by `parisek/styleguide`'s own default — a project that
	 * moves it passes the new path to `install()`.
	 */
	public const SCREEN_RELATIVE = 'static/templates/component/maintenance/maintenance.html';

	/**
	 * Marker identifying a file this class generated, so `install()` can tell
	 * its own output from a drop-in somebody wrote by hand and refuse to
	 * overwrite the latter.
	 */
	public const MARKER = 'Generated by parisek/timber-kit';

	/**
	 * How long a client is asked to wait, in seconds. Matches the 10 minutes
	 * after which WordPress itself stops honouring `.maintenance`.
	 */
	private const RETRY_AFTER = 600;

	/**
	 * PHP source of one drop-in.
	 *
	 * @param string $theme_directory Theme directory name under `themes/`.
	 * @param string $screen_relative Screen path relative to the theme root.
	 */
	public static function source( string $theme_directory, string $screen_relative = self::SCREEN_RELATIVE ): string {
		$screen = sprintf(
			"WP_CONTENT_DIR . '/themes/%s/%s'",
			addslashes( $theme_directory ),
			addslashes( ltrim( $screen_relative, '/' ) )
		);

		$marker  = self::MARKER;
		$retry   = self::RETRY_AFTER;
		$command = 'wp timber-kit outage-drop-ins install';

		return <<<PHP
			<?php
			/**
			 * Outage screen. {$marker} — re-run `{$command}` after moving the theme.
			 *
			 * Runs before plugins and the theme, and with no database. Nothing here
			 * may call a WordPress function or load Composer: none of that exists yet.
			 *
			 * WordPress `require_once`s this file and then calls `die()`, so returning
			 * early would serve a blank page. Every path below prints something.
			 */

			\$screen = {$screen};

			http_response_code( 503 );
			header( 'Retry-After: {$retry}' );
			header( 'Content-Type: text/html; charset=utf-8' );
			header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );

			if ( is_readable( \$screen ) ) {
				readfile( \$screen );
			} else {
				// The theme never rendered its screen, or was renamed. Say the one
				// thing a visitor needs; a blank 503 reads as a broken server.
				echo '<!doctype html><html><head><meta charset="utf-8">'
					. '<title>503</title></head><body>'
					. '<p>The site is briefly unavailable. Please try again in a few minutes.</p>'
					. '</body></html>';
			}

			PHP;
	}

	/**
	 * Writes both drop-ins into `wp-content/`.
	 *
	 * A drop-in that exists and does NOT carry this class's marker is left
	 * alone and reported: it is somebody's own, and silently replacing it is
	 * how a site loses a customisation nobody remembers making.
	 *
	 * @param string $content_dir     Absolute path to `wp-content`.
	 * @param string $theme_directory Theme directory name under `themes/`.
	 * @param string $screen_relative Screen path relative to the theme root.
	 * @return array<string, string> Filename => `written`, `unchanged`, or `foreign`.
	 */
	public static function install(
		string $content_dir,
		string $theme_directory,
		string $screen_relative = self::SCREEN_RELATIVE
	): array {
		$source  = self::source( $theme_directory, $screen_relative );
		$results = array();

		foreach ( array_keys( self::DROP_INS ) as $filename ) {
			$path = rtrim( $content_dir, '/' ) . '/' . $filename;

			if ( file_exists( $path ) ) {
				$existing = (string) file_get_contents( $path );

				if ( ! str_contains( $existing, self::MARKER ) ) {
					$results[ $filename ] = 'foreign';
					continue;
				}

				if ( $existing === $source ) {
					$results[ $filename ] = 'unchanged';
					continue;
				}
			}

			$results[ $filename ] = false === file_put_contents( $path, $source ) ? 'failed' : 'written';
		}

		return $results;
	}

	/**
	 * Removes drop-ins this class generated, leaving any others in place.
	 *
	 * @param string $content_dir Absolute path to `wp-content`.
	 * @return array<string, string> Filename => `removed`, `absent`, or `foreign`.
	 */
	public static function remove( string $content_dir ): array {
		$results = array();

		foreach ( array_keys( self::DROP_INS ) as $filename ) {
			$path = rtrim( $content_dir, '/' ) . '/' . $filename;

			if ( ! file_exists( $path ) ) {
				$results[ $filename ] = 'absent';
				continue;
			}

			if ( ! str_contains( (string) file_get_contents( $path ), self::MARKER ) ) {
				$results[ $filename ] = 'foreign';
				continue;
			}

			$results[ $filename ] = unlink( $path ) ? 'removed' : 'failed';
		}

		return $results;
	}
}
