<?php

declare(strict_types=1);

namespace Parisek\TimberKit;

/**
 * Generates and installs the three WordPress drop-ins that serve the theme's
 * prerendered outage screen.
 *
 * WordPress shows a fallback screen in three states this covers, and in none of
 * them can the theme render one:
 *
 * - a `.maintenance` file in the site root — written by
 *   `wp maintenance-mode activate`, and by core itself during every core and
 *   plugin update. Read by `wp_maintenance()` in `wp-settings.php`, before
 *   plugins and theme.
 * - an unreachable database — `wpdb::dead_db()`, with no options table to ask
 *   anything of.
 * - a fatal PHP error — `WP_Fatal_Error_Handler::display_error_template()`,
 *   which `require_once`s `php-error.php` in place of core's own text.
 *
 * All three `require_once` their drop-in, and none sends a status header
 * first. So the drop-in owns its own status, and it must never `return` early:
 * for the first two, control does not go back to WordPress at all — it goes to
 * `die()` — and a returning drop-in produces a blank page.
 *
 * The fatal-error state differs from its siblings in two ways that the table
 * below encodes, and neither is cosmetic:
 *
 * - **Status `500`, not `503`.** `503` means a planned, bounded outage, and
 *   monitoring reads it that way — some of it suppresses alerts on a `503`
 *   carrying `Retry-After`. A crash is neither planned nor bounded, and the
 *   one thing it must not do is look routine.
 * - **No `Retry-After`.** Nobody knows when a crash clears. The header would
 *   be a guess presented as a promise.
 *
 * The three states cannot collide: the fatal handler returns immediately when
 * `wp_is_maintenance_mode()` holds, so an update serves `maintenance.php` and
 * never a `500`.
 *
 * `php-error.php` also runs *inside* a loaded WordPress, unlike its two
 * siblings — its own banner still forbids calling a WordPress function. That
 * is deliberate: one shape for three files is worth more than an accurate
 * description of a context nothing generated here depends on.
 *
 * **The generated files depend on nothing.** No Composer autoloader, no
 * WordPress function beyond the `WP_CONTENT_DIR` constant, no database. At the
 * moment they run, that is all there is. This class is therefore a source-code
 * generator rather than a runtime: what ships to `wp-content/` is a flat file
 * a human can read in ten seconds.
 *
 * The screen they serve is prerendered by `parisek/styleguide`'s
 * `maintenance:render`. See the theme's own outage documentation.
 */
class OutageScreen {

	/**
	 * Drop-in filename => the contract that file ships with.
	 *
	 * `covers` is prose, for messages. `status` and `retry` are the two things
	 * the generated file does differently per state; `retry` is null where no
	 * honest estimate exists. Keeping all three here means the whole surface is
	 * one table a reader can compare row by row, rather than a condition inside
	 * the generator.
	 *
	 * `context` is the one sentence in the generated banner that is not true of
	 * every file: two of these run before WordPress exists, and the third runs
	 * inside it. The rule underneath that sentence is identical in all three —
	 * see {@see self::source()}.
	 *
	 * @var array<string, array{covers: string, status: int, retry: int|null, context: string}>
	 */
	public const DROP_INS = array(
		'maintenance.php' => array(
			'covers'  => 'deploy or core update',
			'status'  => 503,
			'retry'   => 600,
			'context' => 'Runs before plugins and the theme, and with no database.',
		),
		'db-error.php'    => array(
			'covers'  => 'database unreachable',
			'status'  => 503,
			'retry'   => 600,
			'context' => 'Runs before plugins and the theme, and with no database.',
		),
		'php-error.php'   => array(
			'covers'  => 'fatal PHP error',
			'status'  => 500,
			'retry'   => null,
			'context' => 'Runs inside a crashed WordPress, from the shutdown handler.',
		),
	);

	/**
	 * Where the theme's render command writes the screen, relative to the
	 * theme root. Fixed by `parisek/styleguide`'s own default — a project that
	 * moves it passes the new path to `install()`.
	 */
	public const SCREEN_RELATIVE = 'static/templates/component/maintenance/maintenance.html';

	/**
	 * Marker identifying a file this class generated, so `install()` can tell
	 * its own output from a drop-in somebody wrote by hand and refuse to
	 * overwrite the latter.
	 *
	 * Deliberately a machine-shaped token rather than a sentence: the marker
	 * decides whether a file may be overwritten or deleted, and a prose
	 * attribution line ("Generated by parisek/timber-kit") is exactly the kind
	 * of string somebody copies into a drop-in of their own.
	 */
	public const MARKER = '@generated parisek/timber-kit outage-screen';

	/**
	 * PHP source of one drop-in.
	 *
	 * The `$filename` default keeps the two-argument call working. It is also
	 * the reason the three drop-ins must never be generated by one shared
	 * call: a caller that computes the source once and writes it to every
	 * filename produces two correct files and one that lies about its status.
	 *
	 * @param string $theme_directory Theme directory name under `themes/`.
	 * @param string $screen_relative Screen path relative to the theme root.
	 * @param string $filename        Which drop-in to generate; a key of {@see self::DROP_INS}.
	 *
	 * @throws \InvalidArgumentException When `$filename` is not a known drop-in.
	 */
	public static function source(
		string $theme_directory,
		string $screen_relative = self::SCREEN_RELATIVE,
		string $filename = 'maintenance.php'
	): string {
		if ( ! isset( self::DROP_INS[ $filename ] ) ) {
			throw new \InvalidArgumentException(
				sprintf( '%s is not a drop-in this class generates.', $filename )
			);
		}

		$contract = self::DROP_INS[ $filename ];
		// var_export(), not addslashes(): addslashes() escapes a double quote
		// as \" — which a single-quoted PHP literal does NOT decode, so the
		// generated file compiles fine and then reads a path with a stray
		// backslash in it. var_export() emits a literal that round-trips.
		$screen = sprintf(
			'WP_CONTENT_DIR . %s',
			var_export( '/themes/' . $theme_directory . '/' . ltrim( $screen_relative, '/' ), true )
		);

		$marker  = self::MARKER;
		$status  = $contract['status'];
		$context = $contract['context'];
		$command = 'wp timber-kit outage-screen install';

		// Emitted as a whole line so the generated file carries no empty
		// header call where a state has no honest estimate to give.
		$retry_line = null === $contract['retry']
			? ''
			: sprintf( "\nheader( 'Retry-After: %d' );", $contract['retry'] );

		return <<<PHP
			<?php
			/**
			 * Outage screen. {$marker} — re-run `{$command}` after moving the theme.
			 *
			 * {$context} Nothing here may call a
			 * WordPress function or load Composer: whatever is loaded at this point
			 * is not something an outage screen may depend on.
			 *
			 * WordPress `require_once`s this file and prints nothing of its own
			 * afterwards, so returning early would serve a blank page. Every path
			 * below prints something.
			 */

			\$screen = {$screen};

			http_response_code( {$status} );{$retry_line}
			header( 'Content-Type: text/html; charset=utf-8' );
			header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );

			if ( is_readable( \$screen ) ) {
				readfile( \$screen );
			} else {
				// The theme never rendered its screen, or was renamed. Say the one
				// thing a visitor needs; a blank error reads as a broken server.
				echo '<!doctype html><html><head><meta charset="utf-8">'
					. '<title>{$status}</title></head><body>'
					. '<p>The site is briefly unavailable. Please try again in a few minutes.</p>'
					. '</body></html>';
			}

			PHP;
	}

	/**
	 * Writes every drop-in into `wp-content/`.
	 *
	 * A drop-in that exists and does NOT carry this class's marker is left
	 * alone and reported: it is somebody's own, and silently replacing it is
	 * how a site loses a customisation nobody remembers making.
	 *
	 * @param string $content_dir     Absolute path to `wp-content`.
	 * @param string $theme_directory Theme directory name under `themes/`.
	 * @param string $screen_relative Screen path relative to the theme root.
	 * @return array<string, string> Filename => `written`, `unchanged`, or `foreign`.
	 */
	public static function install(
		string $content_dir,
		string $theme_directory,
		string $screen_relative = self::SCREEN_RELATIVE
	): array {
		$results = array();

		foreach ( array_keys( self::DROP_INS ) as $filename ) {
			// Per file, not once above the loop: the three drop-ins no longer
			// share a source, and hoisting this back out would write one of
			// them with another's status.
			$source = self::source( $theme_directory, $screen_relative, $filename );
			$path   = rtrim( $content_dir, '/' ) . '/' . $filename;

			if ( file_exists( $path ) ) {
				$existing = (string) file_get_contents( $path );

				if ( ! str_contains( $existing, self::MARKER ) ) {
					$results[ $filename ] = 'foreign';
					continue;
				}

				if ( $existing === $source ) {
					$results[ $filename ] = 'unchanged';
					continue;
				}
			}

			$results[ $filename ] = self::write( $path, $source ) ? 'written' : 'failed';
		}

		return $results;
	}

	/**
	 * Writes a drop-in atomically.
	 *
	 * A plain `file_put_contents()` truncates the target first. These two
	 * files are `require_once`d by live requests — reinstalling while
	 * `.maintenance` is active is a normal thing to do — and a request landing
	 * mid-write would parse half a file. Writing beside the target and
	 * renaming makes the swap atomic on the same filesystem.
	 */
	private static function write( string $path, string $source ): bool {
		$temp    = $path . '.tmp';
		$written = file_put_contents( $temp, $source );

		if ( strlen( $source ) !== $written ) {
			// A short write is not a failure to file_put_contents(), which
			// returns the byte count. Treat it as one: a truncated drop-in is
			// worse than none.
			@unlink( $temp );
			return false;
		}

		if ( ! rename( $temp, $path ) ) {
			@unlink( $temp );
			return false;
		}

		return true;
	}

	/**
	 * Removes drop-ins this class generated, leaving any others in place.
	 *
	 * @param string $content_dir Absolute path to `wp-content`.
	 * @return array<string, string> Filename => `removed`, `absent`, or `foreign`.
	 */
	public static function remove( string $content_dir ): array {
		$results = array();

		foreach ( array_keys( self::DROP_INS ) as $filename ) {
			$path = rtrim( $content_dir, '/' ) . '/' . $filename;

			if ( ! file_exists( $path ) ) {
				$results[ $filename ] = 'absent';
				continue;
			}

			if ( ! str_contains( (string) file_get_contents( $path ), self::MARKER ) ) {
				$results[ $filename ] = 'foreign';
				continue;
			}

			$results[ $filename ] = unlink( $path ) ? 'removed' : 'failed';
		}

		return $results;
	}
}
